name: CI to check Merkle Code

on:
  pull_request:
    paths:
      - 'merkle/**'
  push:
    branches: ["main"]
    paths:
      - 'merkle/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./merkle
    steps:
      
      - uses: actions/checkout@v4
      - name: Install Protobuf Compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
              access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              region: eu-west-3
      - name: Test AWS CLI Command
        run: |
            aws s3 ls
      - name: Build
        run: cargo build --release
      - name: Test 
        run: cargo test